sudo: required
services:
  - docker

before_install:
#production Dockerfile does not allow us run any tests
  - docker build -t vladstepanov/react-test -f ./client/Dockerfile.dev ./client
#look at the dir client - to get build context

#this section - is primary test running section
#if any of scripts that we added here finishes with status code
# other than 0 - Travis CI is going to assume that build failed
script:
  - docker run vladstepanov/react-test npm test -- --coverage
#  -  docker run -e CI=true vladstepanov/react-test npm run test
after_success:
  - docker build -t vladstepanov/multi-client ./client
  - docker build -t vladstepanov/multi-nginx ./nginx
  - docker build -t vladstepanov/multi-server ./server
  - docker build -t vladstepanov/multi-worker ./worker
# Log in to the docker CLI
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
#  - docker push vladstepanov/multi-client
#  - docker push vladstepanov/multi-nginx
#  - docker push vladstepanov/multi-server
#  - docker push vladstepanov/multi-worker
#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "multi-docker"
#  env: "MultiDocker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-603648456548"
#  bucket_path: "docker-multi"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"


